//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import Foundation


/// Feature flags for development and testing.
///
/// Set these via Xcode scheme arguments or environment variables.
enum FeatureFlags {
    /// Disables the backend (uses local-only mode). Accepts both --disableBackend and legacy --disableFirebase.
    static let disableBackend = CommandLine.arguments.contains("--disableBackend") || CommandLine.arguments.contains("--disableFirebase")

    /// Legacy alias for disableBackend.
    static let disableFirebase = disableBackend

    /// Connects to Firebase Emulator instead of production.
    static let useFirebaseEmulator = CommandLine.arguments.contains("--useFirebaseEmulator")

    /// Skips the onboarding flow (for UI testing).
    static let skipOnboarding = CommandLine.arguments.contains("--skipOnboarding")

    /// Sets up a test account on launch (for UI testing).
    static let setupTestAccount = CommandLine.arguments.contains("--setupTestAccount")
}
