//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import Foundation


/// Feature flags for development and testing.
///
/// Set these via Xcode scheme arguments or environment variables.
enum FeatureFlags {
    /// Disables Firebase (uses local-only mode).
    static let disableFirebase = CommandLine.arguments.contains("--disableFirebase")

    /// Connects to Firebase Emulator instead of production.
    static let useFirebaseEmulator = CommandLine.arguments.contains("--useFirebaseEmulator")

    /// Skips the onboarding flow (for UI testing).
    static let skipOnboarding = CommandLine.arguments.contains("--skipOnboarding")

    /// Sets up a test account on launch (for UI testing).
    static let setupTestAccount = CommandLine.arguments.contains("--setupTestAccount")
}
