//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import Foundation


/// Constants for UserDefaults / AppStorage keys.
enum StorageKeys {
    static let onboardingFlowComplete = "onboardingFlowComplete"
    static let homeTabSelection = "homeTabSelection"
    // __INJECT_STORAGE_KEYS__
}
