//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//
// SMOKE TESTS — Pre-deployment validation
// These tests run before every TestFlight upload to catch critical issues:
//   1. App launches without crashing
//   2. Onboarding flow is accessible
//   3. All feature tabs load
//   4. Account signup UI is reachable
//
// Run: xcodebuild test -scheme {{ProjectName}} -destination 'platform=iOS Simulator,name=iPhone 16'
// Or:  ./scripts/build-and-deploy.sh (runs these automatically)
//

import XCTest


final class SmokeTests: XCTestCase {
    var app: XCUIApplication!

    override func setUpWithError() throws {
        continueAfterFailure = false
        app = XCUIApplication()
        app.launchArguments += ["--resetTestState"]
    }

    // ─── TEST 1: App launches without crashing ───
    @MainActor
    func testAppLaunches() throws {
        app.launch()
        // If we get here, the app didn't crash on launch
        // Wait a moment for any async initialization
        Thread.sleep(forTimeInterval: 2)
        XCTAssertTrue(app.exists, "App should exist after launch")
    }

    // ─── TEST 2: App launches with Firebase disabled (offline mode) ───
    @MainActor
    func testAppLaunchesOffline() throws {
        app.launchArguments = ["--disableFirebase"]
        app.launch()
        Thread.sleep(forTimeInterval: 2)
        XCTAssertTrue(app.exists, "App should launch even with Firebase disabled")
    }

    // ─── TEST 3: Skip onboarding and verify home screen ───
    @MainActor
    func testHomeScreenLoads() throws {
        app.launchArguments = ["--disableFirebase", "--skipOnboarding"]
        app.launch()
        
        // The home screen should show a tab bar
        let tabBar = app.tabBars.firstMatch
        XCTAssertTrue(tabBar.waitForExistence(timeout: 10), "Tab bar should appear on home screen")
    }

    // ─── TEST 4: All tabs are accessible ───
    @MainActor
    func testAllTabsAccessible() throws {
        app.launchArguments = ["--disableFirebase", "--skipOnboarding"]
        app.launch()
        
        let tabBar = app.tabBars.firstMatch
        XCTAssertTrue(tabBar.waitForExistence(timeout: 10), "Tab bar should exist")
        
        // Tap each tab and verify it responds
        let tabs = tabBar.buttons.allElementsBoundByIndex
        XCTAssertGreaterThan(tabs.count, 0, "Should have at least one tab")
        
        for tab in tabs {
            tab.tap()
            Thread.sleep(forTimeInterval: 0.5)
            XCTAssertTrue(tab.isSelected || tab.isHittable, "Tab '\(tab.label)' should be tappable")
        }
    }

    // ─── TEST 5: Onboarding flow starts correctly ───
    @MainActor
    func testOnboardingFlowStarts() throws {
        app.launchArguments = ["--disableFirebase"]
        app.launch()
        
        // On first launch, onboarding should appear
        // Look for common onboarding elements
        let welcomeExists = app.staticTexts.matching(NSPredicate(format: "label CONTAINS[c] 'welcome' OR label CONTAINS[c] 'get started' OR label CONTAINS[c] 'continue'")).firstMatch.waitForExistence(timeout: 10)
        
        // Either we see onboarding OR the app went straight to home (if skipOnboarding was persisted)
        let tabBarExists = app.tabBars.firstMatch.waitForExistence(timeout: 2)
        
        XCTAssertTrue(welcomeExists || tabBarExists, "Should show either onboarding or home screen")
    }

    // ─── TEST 6: Account signup UI is reachable ───
    @MainActor
    func testSignupUIReachable() throws {
        app.launchArguments = ["--disableFirebase"]
        app.launch()
        
        // Navigate through onboarding to find signup
        // Try tapping Continue/Next buttons to progress
        for _ in 0..<5 {
            let continueButton = app.buttons.matching(NSPredicate(format: "label CONTAINS[c] 'continue' OR label CONTAINS[c] 'next' OR label CONTAINS[c] 'get started'")).firstMatch
            if continueButton.waitForExistence(timeout: 2) {
                continueButton.tap()
                Thread.sleep(forTimeInterval: 1)
            }
            
            // Check if we've reached a signup/login screen
            let signupField = app.textFields.matching(NSPredicate(format: "placeholderValue CONTAINS[c] 'email' OR placeholderValue CONTAINS[c] 'e-mail'")).firstMatch
            let signupButton = app.buttons.matching(NSPredicate(format: "label CONTAINS[c] 'sign up' OR label CONTAINS[c] 'create account' OR label CONTAINS[c] 'signup'")).firstMatch
            
            if signupField.exists || signupButton.exists {
                // Found signup UI
                return
            }
        }
        
        // If we couldn't find signup, that's OK — the app might skip to home if onboarding was completed before
        let tabBarExists = app.tabBars.firstMatch.waitForExistence(timeout: 2)
        XCTAssertTrue(tabBarExists, "Should reach either signup screen or home screen")
    }
}
