#!/bin/bash
# Supabase Project Setup for {{ProjectName}}
# Generated by SpeziVibe — run once after project creation
#
# This script helps you set up a Supabase project and configure the app.
#
# Prerequisites: A Supabase account (https://supabase.com)
#
# Usage:
#   ./scripts/supabase-setup.sh
#   ./scripts/supabase-setup.sh --url https://xxx.supabase.co --key sb_xxx

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
PLIST_PATH="$PROJECT_DIR/Sources/Resources/Supabase.plist"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}⚠${NC} $1"; }

SUPABASE_URL=""
SUPABASE_KEY=""

# Parse args
while [[ $# -gt 0 ]]; do
    case $1 in
        --url) SUPABASE_URL="$2"; shift 2 ;;
        --key) SUPABASE_KEY="$2"; shift 2 ;;
        *) shift ;;
    esac
done

echo "🟢 Supabase Setup for {{DisplayName}}"
echo ""

# Prompt if not provided
if [[ -z "$SUPABASE_URL" ]]; then
    echo "Enter your Supabase project URL"
    echo "(from https://supabase.com/dashboard/project/_/settings/api)"
    read -rp "URL: " SUPABASE_URL
fi

if [[ -z "$SUPABASE_KEY" ]]; then
    echo ""
    echo "Enter your Supabase anon/public key"
    echo "(from the same settings page)"
    read -rp "Key: " SUPABASE_KEY
fi

# Update Supabase.plist
echo ""
echo "📄 Updating Supabase.plist..."
cat > "$PLIST_PATH" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>SUPABASE_URL</key>
	<string>${SUPABASE_URL}</string>
	<key>SUPABASE_ANON_KEY</key>
	<string>${SUPABASE_KEY}</string>
</dict>
</plist>
PLIST
log "Supabase.plist updated"

# Create profiles table SQL
echo ""
echo "📋 Creating database setup SQL..."
SQL_PATH="$PROJECT_DIR/scripts/supabase-schema.sql"
cat > "$SQL_PATH" << 'SQL'
-- Supabase Schema for {{ProjectName}}
-- Run this in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql

-- User profiles
create table if not exists profiles (
    id uuid references auth.users(id) on delete cascade primary key,
    email text,
    display_name text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- Enable RLS
alter table profiles enable row level security;

-- Users can read/write their own profile
create policy "Users can view own profile"
    on profiles for select
    using (auth.uid() = id);

create policy "Users can update own profile"
    on profiles for update
    using (auth.uid() = id);

create policy "Users can insert own profile"
    on profiles for insert
    with check (auth.uid() = id);

-- User data (generic key-value store)
create table if not exists user_data (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    table_name text not null,
    data jsonb not null,
    created_at timestamptz default now()
);

alter table user_data enable row level security;

create policy "Users can manage own data"
    on user_data for all
    using (auth.uid() = user_id);

-- Storage bucket for user files
insert into storage.buckets (id, name, public)
values ('user-files', 'user-files', false)
on conflict (id) do nothing;

create policy "Users can upload own files"
    on storage.objects for insert
    with check (auth.uid()::text = (storage.foldername(name))[1]);

create policy "Users can view own files"
    on storage.objects for select
    using (auth.uid()::text = (storage.foldername(name))[1]);
SQL
log "Schema SQL saved to scripts/supabase-schema.sql"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 Supabase configuration complete!"
echo ""
echo "   URL: $SUPABASE_URL"
echo ""
echo "   Next steps:"
echo "   1. Go to your Supabase Dashboard → SQL Editor"
echo "   2. Run the SQL in: scripts/supabase-schema.sql"
echo "   3. Enable Email auth in Authentication → Providers"
echo "   4. Build and run!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
