//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import OSLog
import Spezi
import SpeziAccount
import Supabase
import SwiftUI
// __INJECT_STANDARD_IMPORTS__


actor {{ProjectName}}Standard: Standard, EnvironmentAccessible {
    @Application(\.logger) private var logger

    private var client: SupabaseClient {
        SupabaseConfig.shared.client
    }

    // __INJECT_STANDARD_CONFORMANCES__


    /// Store data to Supabase for the current user.
    func store(_ data: [String: Any], table: String) async throws {
        guard let userId = try? await client.auth.session.user.id else {
            logger.warning("Cannot store data — user not authenticated")
            return
        }

        var record = data
        record["user_id"] = userId.uuidString

        try await client.from(table)
            .upsert(record)
            .execute()

        logger.info("Stored record to \(table)")
    }

    /// Fetch data from Supabase for the current user.
    func fetch<T: Decodable>(from table: String, type: T.Type) async throws -> [T] {
        guard let userId = try? await client.auth.session.user.id else {
            logger.warning("Cannot fetch data — user not authenticated")
            return []
        }

        return try await client.from(table)
            .select()
            .eq("user_id", value: userId.uuidString)
            .execute()
            .value
    }

    /// Upload data to Supabase Storage.
    func upload(data: Data, bucket: String, path: String) async throws -> String {
        try await client.storage
            .from(bucket)
            .upload(
                path: path,
                file: data,
                options: FileOptions(contentType: "application/octet-stream")
            )

        let url = try client.storage
            .from(bucket)
            .getPublicURL(path: path)

        return url.absoluteString
    }
}
