//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import Foundation
import Supabase


/// Central Supabase client configuration.
///
/// Reads connection details from `Supabase.plist` bundled in the app resources.
/// To configure: update `Sources/Resources/Supabase.plist` with your project URL and anon key
/// from https://supabase.com/dashboard/project/_/settings/api
final class SupabaseConfig {
    static let shared = SupabaseConfig()

    let client: SupabaseClient

    private init() {
        guard let plistPath = Bundle.main.path(forResource: "Supabase", ofType: "plist"),
              let plistData = FileManager.default.contents(atPath: plistPath),
              let plist = try? PropertyListSerialization.propertyList(from: plistData, format: nil) as? [String: String],
              let urlString = plist["SUPABASE_URL"], !urlString.isEmpty,
              let url = URL(string: urlString),
              let anonKey = plist["SUPABASE_ANON_KEY"], !anonKey.isEmpty else {

            // Fallback for testing / --disableFirebase mode
            if FeatureFlags.disableFirebase {
                self.client = SupabaseClient(
                    supabaseURL: URL(string: "https://placeholder.supabase.co")!,
                    supabaseKey: "placeholder"
                )
                return
            }

            fatalError("""
            Supabase.plist is missing or incomplete.
            Please update Sources/Resources/Supabase.plist with:
              - SUPABASE_URL: Your Supabase project URL
              - SUPABASE_ANON_KEY: Your Supabase anon/public key

            Get these from: https://supabase.com/dashboard/project/_/settings/api
            """)
        }

        self.client = SupabaseClient(supabaseURL: url, supabaseKey: anonKey)
    }
}
