//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import Foundation
import OSLog
import Spezi
import SpeziAccount
import Supabase
import Auth


private let logger = Logger(subsystem: "{{ProjectName}}", category: "SupabaseAccountService")


/// Supabase-backed account service for SpeziAccount.
///
/// Provides email/password signup and login via Supabase Auth.
/// User profile data is stored in a `profiles` table in Supabase.
actor SupabaseAccountService: AccountService {
    static let supportedKeys = AccountKeyCollection {
        \.accountId
        \.userId
        \.name
    }

    @AccountReference private var account: Account
    @Application(\.logger) private var appLogger

    private var client: SupabaseClient {
        SupabaseConfig.shared.client
    }

    init() {}


    func login(userId: String, password: String) async throws {
        logger.info("Logging in user: \(userId)")
        let response = try await client.auth.signIn(
            email: userId,
            password: password
        )
        logger.info("Login successful for: \(response.user.email ?? "unknown")")
    }

    func signUp(signupDetails: AccountDetails) async throws {
        let email = signupDetails.userId
        let password = signupDetails.password ?? ""

        logger.info("Signing up user: \(email)")
        let response = try await client.auth.signUp(
            email: email,
            password: password
        )

        // Store profile data
        if let name = signupDetails.name {
            try await client.from("profiles").upsert([
                "id": response.user.id.uuidString,
                "email": email,
                "display_name": name.formatted(),
            ]).execute()
        }

        logger.info("Signup successful for: \(response.user.email ?? "unknown")")
    }

    func logout() async throws {
        try await client.auth.signOut()
        logger.info("User logged out")
    }

    func delete() async throws {
        // Note: Supabase user deletion requires admin privileges
        // This signs out the user; actual deletion should be handled server-side
        try await client.auth.signOut()
        logger.warning("User signed out (full deletion requires server-side admin action)")
    }
}
