//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziAccount
import SwiftUI


struct AccountSheet: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(Account.self) private var account: Account?

    /// When true, the sheet auto-dismisses after the user signs in.
    var dismissAfterSignIn = false

    var body: some View {
        NavigationStack {
            AccountOverview(close: .showCloseButton)
        }
        .onChange(of: account?.signedIn) {
            if dismissAfterSignIn, account?.signedIn == true {
                dismiss()
            }
        }
    }
}
