//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziAccount
import SwiftUI


struct AccountButton: View {
    @Binding var isPresented: Bool
    @State private var internalPresented = false
    private let usesInternalState: Bool


    init(isPresented: Binding<Bool>) {
        _isPresented = isPresented
        usesInternalState = false
    }


    init() {
        _isPresented = .constant(false)
        usesInternalState = true
    }


    private var effectiveBinding: Binding<Bool> {
        if usesInternalState {
            return $internalPresented
        }
        return $isPresented
    }


    var body: some View {
        Button(action: { effectiveBinding.wrappedValue = true }) {
            Image(systemName: "person.circle")
        }
        .accessibilityLabel("Account")
        .sheet(isPresented: effectiveBinding) {
            AccountSheet()
        }
    }
}
