//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziAccount
import SwiftUI


struct AccountButton: View {
    @Binding var isPresented: Bool


    init(isPresented: Binding<Bool> = .constant(false)) {
        _isPresented = isPresented
    }


    var body: some View {
        Button(action: { isPresented = true }) {
            Image(systemName: "person.circle")
        }
    }
}
