//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SwiftUI


/// App-wide theme colors and styling.
enum AppTheme {
    /// Primary brand color (hex: {{primaryColor}})
    static let primaryColor = Color(
        red: {{primaryColorR}},
        green: {{primaryColorG}},
        blue: {{primaryColorB}}
    )
}
