//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziAccount
import SpeziOnboarding
import SpeziViews
import SwiftUI


struct AccountOnboarding: View {
    @Environment(ManagedNavigationStack.Path.self) private var path


    var body: some View {
        AccountSetup { _ in
            // setup complete
        } header: {
            AccountSetupHeader()
        } continue: {
            Button("Continue") {
                path.nextStep()
            }
            .frame(maxWidth: .infinity, minHeight: 38)
            .buttonStyle(.borderedProminent)
        }
    }
}
