//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import class ModelsR4.Questionnaire
import Foundation


extension Bundle {
    /// Load a FHIR Questionnaire from a bundled JSON file.
    func questionnaire(withName name: String) -> Questionnaire {
        guard let resourceURL = url(forResource: name, withExtension: "json") else {
            fatalError("Could not find questionnaire \(name).json in bundle.")
        }

        do {
            let data = try Data(contentsOf: resourceURL)
            return try JSONDecoder().decode(Questionnaire.self, from: data)
        } catch {
            fatalError("Could not decode questionnaire \(name): \(error)")
        }
    }
}
