//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import class ModelsR4.Questionnaire
import Foundation


enum QuestionnaireError: LocalizedError {
    case notFound(String)
    case decodingFailed(String, Error)

    var errorDescription: String? {
        switch self {
        case .notFound(let name):
            return "Could not find questionnaire \(name).json in bundle."
        case .decodingFailed(let name, let error):
            return "Could not decode questionnaire \(name): \(error.localizedDescription)"
        }
    }
}


extension Bundle {
    /// Load a FHIR Questionnaire from a bundled JSON file.
    func questionnaire(withName name: String) throws -> Questionnaire {
        guard let resourceURL = url(forResource: name, withExtension: "json") else {
            throw QuestionnaireError.notFound(name)
        }

        do {
            let data = try Data(contentsOf: resourceURL)
            return try JSONDecoder().decode(Questionnaire.self, from: data)
        } catch {
            throw QuestionnaireError.decodingFailed(name, error)
        }
    }
}
