//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziHealthKit
import SpeziOnboarding
import SpeziViews
import SwiftUI


struct HealthKitPermissions: View {
    @Environment(HealthKit.self) private var healthKit
    @Environment(ManagedNavigationStack.Path.self) private var path


    var body: some View {
        OnboardingView(
            title: "HealthKit Access",
            subtitle: "{{DisplayName}} can access your Apple Health data to provide personalized health insights.",
            areas: [
                .init(
                    icon: { Image(systemName: "heart.text.square.fill").foregroundStyle(.red) },
                    title: "Health Data",
                    description: "Access step count, heart rate, and more from Apple Health."
                )
            ],
            actionText: "Grant Access",
            action: {
                try await healthKit.askForAuthorization()
                path.nextStep()
            }
        )
    }
}
