//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziHealthKit
import SpeziOnboarding
import SwiftUI


struct HealthKitPermissions: View {
    @Environment(HealthKit.self) private var healthKit
    @Environment(OnboardingNavigationPath.self) private var onboardingNavigationPath


    var body: some View {
        OnboardingView(
            contentView: {
                VStack(spacing: 16) {
                    OnboardingTitleView(
                        title: "HealthKit Access",
                        subtitle: "{{DisplayName}} can access your Apple Health data to provide personalized health insights."
                    )
                    Spacer()
                    Image(systemName: "heart.text.square.fill")
                        .font(.system(size: 100))
                        .foregroundColor(.red)
                        .accessibilityHidden(true)
                    Spacer()
                }
            },
            actionView: {
                OnboardingActionsView("Grant Access") {
                    healthKit.askForAuthorization()
                    onboardingNavigationPath.nextStep()
                }
            }
        )
    }
}
