//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziHealthKit


/// HealthKit data collection configuration.
/// Modify this to change which health data types the app collects.
extension HealthKit {
    static var appConfiguration: HealthKit {
        HealthKit {
{{healthKitCollectSamples}}
        }
    }
}
