//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziConsent
import SpeziOnboarding
import SpeziViews
import SwiftUI


struct Consent: View {
    @Environment(ManagedNavigationStack.Path.self) private var path
    @State private var viewState: ViewState = .idle


    var body: some View {
        OnboardingConsentView(
            consentDocument: nil,
            viewState: $viewState
        ) {
            path.nextStep()
        }
    }
}
