//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziConsent
import SpeziOnboarding
import SwiftUI


struct Consent: View {
    @Environment(OnboardingNavigationPath.self) private var onboardingNavigationPath


    var body: some View {
        OnboardingConsentView(
            header: {
                OnboardingTitleView(
                    title: "Consent",
                    subtitle: "Please review and sign the consent document below."
                )
            },
            documentIdentifier: "consent-form",
            exportConfiguration: .init(paperSize: .usLetter)
        ) {
            onboardingNavigationPath.nextStep()
        }
    }
}
