//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziOnboarding
import SpeziViews
import SwiftUI


struct InterestingModules: View {
    @Environment(ManagedNavigationStack.Path.self) private var path


    var body: some View {
        OnboardingView(
            title: "What This App Offers",
            subtitle: "{{DisplayName}} includes the following features.",
            areas: [
                .init(
                    icon: { Image(systemName: "heart.circle.fill").foregroundStyle(.pink) },
                    title: "Your Health Companion",
                    description: "Track and manage your health journey with personalized tools."
                ),
                .init(
                    icon: { Image(systemName: "lock.shield").foregroundStyle(.purple) },
                    title: "Secure & Private",
                    description: "Your health data is encrypted and stays under your control."
                )
            ],
            actionText: "Continue",
            action: {
                path.nextStep()
            }
        )
    }
}
