//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziOnboarding
import SwiftUI


struct InterestingModules: View {
    @Environment(OnboardingNavigationPath.self) private var onboardingNavigationPath


    var body: some View {
        OnboardingView(
            title: "What This App Offers",
            subtitle: "{{DisplayName}} includes the following features.",
            areas: [
                .init(
                    icon: Image(systemName: "list.clipboard"),
                    title: "Track Health Tasks",
                    description: "Stay on top of scheduled health activities and check-ins."
                ),
                .init(
                    icon: Image(systemName: "doc.text.fill"),
                    title: "Health Questionnaires",
                    description: "Complete FHIR-compliant health assessments."
                ),
                .init(
                    icon: Image(systemName: "lock.shield"),
                    title: "Secure & Private",
                    description: "Your health data is encrypted and stays under your control."
                )
            ],
            actionText: "Continue",
            action: {
                onboardingNavigationPath.nextStep()
            }
        )
    }
}
