//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziNotifications
import SpeziOnboarding
import SwiftUI


struct NotificationPermissions: View {
    @Environment(OnboardingNavigationPath.self) private var onboardingNavigationPath
    @Environment(\.notificationSettings) private var notificationSettings


    var body: some View {
        OnboardingView(
            contentView: {
                VStack(spacing: 16) {
                    OnboardingTitleView(
                        title: "Notifications",
                        subtitle: "{{DisplayName}} sends reminders for scheduled health tasks."
                    )
                    Spacer()
                    Image(systemName: "bell.badge.fill")
                        .font(.system(size: 80))
                        .foregroundColor(.orange)
                        .accessibilityHidden(true)
                    Spacer()
                }
            },
            actionView: {
                OnboardingActionsView("Allow Notifications") {
                    do {
                        let center = UNUserNotificationCenter.current()
                        try await center.requestAuthorization(options: [.alert, .badge, .sound])
                    } catch {
                        // User denied, continue anyway
                    }
                    onboardingNavigationPath.nextStep()
                }
            }
        )
    }
}
