//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziOnboarding
import SpeziViews
import SwiftUI
import UserNotifications


struct NotificationPermissions: View {
    @Environment(ManagedNavigationStack.Path.self) private var path


    var body: some View {
        OnboardingView(
            title: "Notifications",
            subtitle: "{{DisplayName}} sends reminders for scheduled health tasks.",
            areas: [
                .init(
                    icon: { Image(systemName: "bell.badge.fill").foregroundStyle(.orange) },
                    title: "Stay on Track",
                    description: "Get timely reminders for health check-ins and tasks."
                )
            ],
            actionText: "Allow Notifications",
            action: {
                do {
                    let center = UNUserNotificationCenter.current()
                    try await center.requestAuthorization(options: [.alert, .badge, .sound])
                } catch {
                    // User denied, continue anyway
                }
                path.nextStep()
            }
        )
    }
}
