//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import XCTest
@testable import {{ProjectName}}


final class {{ProjectName}}Tests: XCTestCase {
    func testAppLaunches() throws {
        // Basic test to verify the app target builds correctly
        XCTAssertTrue(true)
    }
}
