//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziContact
import SwiftUI


struct ContactsView: View {
    @Binding var presentingAccount: Bool

    let contacts = [
        Contact(
            name: PersonNameComponents(givenName: "Jane", familyName: "Doe"),
            title: "Primary Care Physician",
            description: "Your primary care provider.",
            organization: "Health Clinic",
            contactOptions: [
                .call("+1 (555) 123-4567"),
                .email(addresses: ["jane.doe@example.com"], subject: "{{DisplayName}} — Patient Inquiry")
            ]
        )
    ]


    var body: some View {
        NavigationStack {
            ContactsList(contacts: contacts)
                .navigationTitle("Contacts")
                .toolbar {
                    ToolbarItem(placement: .topBarTrailing) {
                        Button("Account", systemImage: "person.circle") {
                            presentingAccount = true
                        }
                    }
                }
        }
    }
}
