//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import Spezi
import SpeziViews
import SwiftUI
// __INJECT_APP_IMPORTS__


@main
struct {{ProjectName}}App: App {
    @UIApplicationDelegateAdaptor({{ProjectName}}Delegate.self) var appDelegate
    @AppStorage(StorageKeys.onboardingFlowComplete) var completedOnboardingFlow = false


    private var showOnboarding: Binding<Bool> {
        Binding(
            get: { !completedOnboardingFlow },
            set: { completedOnboardingFlow = !$0 }
        )
    }


    var body: some Scene {
        WindowGroup {
            ZStack {
                if completedOnboardingFlow {
                    HomeView()
                } else {
                    EmptyView()
                }
            }
            .sheet(isPresented: showOnboarding) {
                OnboardingFlow()
            }
            .spezi(appDelegate)
        }
    }
}
