//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import Spezi
import SpeziViews
import SwiftUI
// __INJECT_DELEGATE_IMPORTS__


class {{ProjectName}}Delegate: SpeziAppDelegate {
    override var configuration: Configuration {
        Configuration(standard: {{ProjectName}}Standard()) {
            // __INJECT_DELEGATE_MODULES__
        }
    }
}
