//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SwiftUI
// __INJECT_HOMEVIEW_IMPORTS__


struct HomeView: View {
    enum Tabs: String {
        case home
        // __INJECT_TAB_CASES__
    }


    @AppStorage(StorageKeys.homeTabSelection) private var selectedTab = Tabs.home
    @State private var presentingAccount = false


    var body: some View {
        TabView(selection: $selectedTab) {
            Tab("Home", systemImage: "house", value: .home) {
                NavigationStack {
                    VStack(spacing: 20) {
                        Image(systemName: "heart.circle.fill")
                            .resizable()
                            .frame(width: 80, height: 80)
                            .foregroundStyle(.pink)
                        Text("Welcome to {{DisplayName}}")
                            .font(.title2)
                            .fontWeight(.semibold)
                        Text("Your digital health companion")
                            .foregroundStyle(.secondary)
                    }
                    .navigationTitle("Home")
                    // __INJECT_HOME_TOOLBAR__
                }
            }
            // __INJECT_TABS__
        }
        .tabViewStyle(.sidebarAdaptable)
        // __INJECT_HOMEVIEW_SHEETS__
    }
}


#Preview {
    HomeView()
}
