//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziOnboarding
import SpeziViews
import SwiftUI
// __INJECT_ONBOARDING_IMPORTS__


/// Multi-step onboarding flow for {{DisplayName}}.
struct OnboardingFlow: View {
    @AppStorage(StorageKeys.onboardingFlowComplete) private var completedOnboardingFlow = false

    // __INJECT_ONBOARDING_STATE__

    var body: some View {
        ManagedNavigationStack(didComplete: $completedOnboardingFlow) {
            Welcome()
            // __INJECT_ONBOARDING_STEPS__
        }
        .interactiveDismissDisabled(!completedOnboardingFlow)
        // __INJECT_ONBOARDING_MODIFIERS__
    }
}


#Preview {
    OnboardingFlow()
}
