//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import OSLog
import Spezi
import SwiftUI
// __INJECT_STANDARD_IMPORTS__


actor {{ProjectName}}Standard: Standard,
                               EnvironmentAccessible
                               // __INJECT_STANDARD_CONFORMANCES__
                               {
    @Application(\.logger) private var logger

    // __INJECT_STANDARD_DEPENDENCIES__

    init() {}

    // __INJECT_STANDARD_METHODS__
}
