//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziOnboarding
import SwiftUI


struct Welcome: View {
    @Environment(OnboardingNavigationPath.self) private var onboardingNavigationPath


    var body: some View {
        OnboardingView(
            title: "Welcome to {{DisplayName}}",
            subtitle: "Your digital health companion",
            areas: [
                .init(
                    icon: Image(systemName: "heart.text.clipboard"),
                    title: "Health Data",
                    description: "Securely manage your health information."
                ),
                .init(
                    icon: Image(systemName: "lock.shield"),
                    title: "Privacy First",
                    description: "Your data stays under your control."
                ),
                .init(
                    icon: Image(systemName: "sparkles"),
                    title: "Powered by Spezi",
                    description: "Built on Stanford's open-source digital health framework."
                )
            ],
            actionText: "Get Started",
            action: {
                onboardingNavigationPath.nextStep()
            }
        )
    }
}


#Preview {
    Welcome()
}
