//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziOnboarding
import SpeziViews
import SwiftUI


struct Welcome: View {
    @Environment(ManagedNavigationStack.Path.self) private var path


    var body: some View {
        OnboardingView(
            title: "Welcome to {{DisplayName}}",
            subtitle: "Your digital health companion",
            areas: [
                .init(
                    icon: { Image(systemName: "heart.text.clipboard").foregroundStyle(.pink) },
                    title: "Health Data",
                    description: "Securely manage your health information."
                ),
                .init(
                    icon: { Image(systemName: "lock.shield").foregroundStyle(.blue) },
                    title: "Privacy First",
                    description: "Your data stays under your control."
                ),
                .init(
                    icon: { Image(systemName: "sparkles").foregroundStyle(.orange) },
                    title: "Powered by Spezi",
                    description: "Built on Stanford's open-source digital health framework."
                )
            ],
            actionText: "Get Started",
            action: {
                path.nextStep()
            }
        )
    }
}
