#!/bin/bash
# Build, archive, and upload {{ProjectName}} to App Store Connect / TestFlight
# Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
#
# Prerequisites:
#   1. App Store Connect API key (.p8) — download from https://appstoreconnect.apple.com/access/integrations/api
#   2. Set the variables below or pass as environment variables
#
# Usage:
#   ./scripts/build-and-deploy.sh              # Build + upload
#   ./scripts/build-and-deploy.sh --build-only # Build only (no upload)
#   ./scripts/build-and-deploy.sh --bump       # Bump build number + build + upload

set -euo pipefail

# ─── CONFIGURATION ───
PROJECT_NAME="{{ProjectName}}"
SCHEME="{{ProjectName}}"
TEAM_ID="${TEAM_ID:-Q922968VSH}"
API_KEY_ID="${API_KEY_ID:-S8RY46W528}"
API_KEY_ISSUER="${API_KEY_ISSUER:-493bc6bd-8a12-42a0-9faa-08dab2890fc5}"
API_KEY_PATH="${API_KEY_PATH:-$HOME/Downloads/AuthKey_${API_KEY_ID}.p8}"

# ─── DERIVED PATHS ───
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ARCHIVE_PATH="/tmp/${PROJECT_NAME}.xcarchive"
EXPORT_PATH="/tmp/${PROJECT_NAME}-export"
EXPORT_PLIST="/tmp/${PROJECT_NAME}-export-options.plist"

cd "$PROJECT_DIR"

# ─── BUMP BUILD NUMBER ───
if [[ "${1:-}" == "--bump" ]]; then
    echo "📈 Bumping build number..."
    CURRENT=$(grep 'CURRENT_PROJECT_VERSION' project.yml | head -1 | sed 's/.*: *"\{0,1\}\([0-9]*\)"\{0,1\}/\1/')
    NEXT=$((CURRENT + 1))
    sed -i '' "s/CURRENT_PROJECT_VERSION: \"*${CURRENT}\"*/CURRENT_PROJECT_VERSION: \"${NEXT}\"/" project.yml
    echo "   Build number: $CURRENT → $NEXT"
    
    # Regenerate xcodeproj
    if command -v xcodegen &>/dev/null; then
        xcodegen generate 2>&1 | head -5
    fi
fi

# ─── SMOKE TESTS ───
if [[ "${1:-}" != "--skip-tests" ]]; then
    echo "🧪 Running smoke tests..."
    TEST_RESULT=$(xcodebuild test \
        -project "${PROJECT_NAME}.xcodeproj" \
        -scheme "$SCHEME" \
        -destination "platform=iOS Simulator,name=iPhone 16" \
        -testPlan "SmokeTests" \
        -only-testing:"${PROJECT_NAME}UITests/SmokeTests" \
        -skipMacroValidation \
        CODE_SIGN_STYLE=Automatic \
        DEVELOPMENT_TEAM="$TEAM_ID" \
        2>&1 | tail -20)

    if echo "$TEST_RESULT" | grep -q "TEST FAILED\|BUILD FAILED"; then
        echo "❌ Smoke tests FAILED! Not deploying."
        echo "$TEST_RESULT"
        echo ""
        echo "Fix the issues above, then run again."
        echo "To skip tests (not recommended): ./scripts/build-and-deploy.sh --skip-tests"
        exit 1
    fi
    echo "✅ All smoke tests passed"
else
    echo "⚠️  Skipping tests (--skip-tests flag)"
fi

# ─── ARCHIVE ───
echo "📦 Archiving ${PROJECT_NAME}..."
xcodebuild archive \
    -project "${PROJECT_NAME}.xcodeproj" \
    -scheme "$SCHEME" \
    -destination "generic/platform=iOS" \
    -archivePath "$ARCHIVE_PATH" \
    -allowProvisioningUpdates \
    -skipMacroValidation \
    CODE_SIGN_STYLE=Automatic \
    DEVELOPMENT_TEAM="$TEAM_ID" \
    2>&1 | tail -3

if [[ $? -ne 0 ]]; then
    echo "❌ Archive failed!"
    exit 1
fi
echo "✅ Archive succeeded"

if [[ "${1:-}" == "--build-only" ]]; then
    echo "📍 Archive at: $ARCHIVE_PATH"
    exit 0
fi

# ─── EXPORT ───
echo "📤 Exporting IPA..."
cat > "$EXPORT_PLIST" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>method</key>
    <string>app-store-connect</string>
    <key>teamID</key>
    <string>${TEAM_ID}</string>
    <key>uploadSymbols</key>
    <true/>
    <key>signingStyle</key>
    <string>automatic</string>
    <key>destination</key>
    <string>export</string>
</dict>
</plist>
EOF

rm -rf "$EXPORT_PATH"
xcodebuild -exportArchive \
    -archivePath "$ARCHIVE_PATH" \
    -exportOptionsPlist "$EXPORT_PLIST" \
    -exportPath "$EXPORT_PATH" \
    -allowProvisioningUpdates \
    -authenticationKeyPath "$API_KEY_PATH" \
    -authenticationKeyID "$API_KEY_ID" \
    -authenticationKeyIssuerID "$API_KEY_ISSUER" \
    2>&1 | tail -3

echo "✅ Export succeeded"

# ─── UPLOAD ───
echo "🚀 Uploading to App Store Connect..."
xcrun altool --upload-app \
    -f "${EXPORT_PATH}/${PROJECT_NAME}.ipa" \
    --type ios \
    --apiKey "$API_KEY_ID" \
    --apiIssuer "$API_KEY_ISSUER" \
    2>&1 | tail -5

echo ""
echo "🎉 Done! Build uploaded to App Store Connect."
echo "   Check TestFlight in ~5-10 minutes."
