#!/bin/bash
# Firebase Project Setup for {{ProjectName}}
# Generated by SpeziVibe — run once after project creation
#
# This script:
#   1. Creates a Firebase project (or uses existing)
#   2. Registers the iOS app
#   3. Downloads GoogleService-Info.plist
#   4. Enables Email/Password authentication
#   5. Creates Firestore database
#   6. Deploys security rules
#   7. Enables Firebase Storage
#
# Prerequisites: npm (for firebase-tools), gcloud CLI
#
# Usage:
#   ./scripts/firebase-setup.sh                          # Interactive
#   ./scripts/firebase-setup.sh --project-id my-app      # Non-interactive
#   ./scripts/firebase-setup.sh --existing my-app         # Use existing project

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
BUNDLE_ID=$(grep 'PRODUCT_BUNDLE_IDENTIFIER' "$PROJECT_DIR/project.yml" | head -1 | sed 's/.*: *//;s/"//g;s/ //g')
DISPLAY_NAME="{{DisplayName}}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}⚠${NC} $1"; }
err()  { echo -e "${RED}✗${NC} $1"; exit 1; }

# ─── Parse Args ───
FIREBASE_PROJECT_ID=""
USE_EXISTING=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --project-id) FIREBASE_PROJECT_ID="$2"; shift 2 ;;
        --existing)   USE_EXISTING="$2"; shift 2 ;;
        *) shift ;;
    esac
done

# ─── Check Prerequisites ───
command -v npx &>/dev/null || err "npx not found. Install Node.js first."
echo "🔥 Firebase Setup for ${DISPLAY_NAME}"
echo "   Bundle ID: ${BUNDLE_ID}"
echo ""

# ─── Create or Select Firebase Project ───
if [[ -n "$USE_EXISTING" ]]; then
    FIREBASE_PROJECT_ID="$USE_EXISTING"
    log "Using existing Firebase project: $FIREBASE_PROJECT_ID"
elif [[ -z "$FIREBASE_PROJECT_ID" ]]; then
    # Generate a project ID from display name
    FIREBASE_PROJECT_ID=$(echo "$DISPLAY_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9-' | head -c 30)
    echo "Creating Firebase project: $FIREBASE_PROJECT_ID"
    npx firebase-tools projects:create "$FIREBASE_PROJECT_ID" --display-name "$DISPLAY_NAME" 2>&1 || {
        warn "Project creation failed — it may already exist. Trying to continue..."
    }
    log "Firebase project ready: $FIREBASE_PROJECT_ID"
fi

# ─── Register iOS App ───
echo ""
echo "📱 Registering iOS app (${BUNDLE_ID})..."
APP_RESULT=$(npx firebase-tools apps:create ios --project "$FIREBASE_PROJECT_ID" --bundle-id="$BUNDLE_ID" 2>&1) || {
    warn "iOS app may already be registered. Continuing..."
}
# Extract App ID
APP_ID=$(echo "$APP_RESULT" | grep "App ID:" | sed 's/.*App ID: //')
if [[ -z "$APP_ID" ]]; then
    # Try to find existing app
    APP_ID=$(npx firebase-tools apps:list ios --project "$FIREBASE_PROJECT_ID" 2>&1 | grep "$BUNDLE_ID" | awk '{print $4}' | head -1)
fi
log "iOS App ID: ${APP_ID:-unknown}"

# ─── Download GoogleService-Info.plist ───
echo ""
echo "📄 Downloading GoogleService-Info.plist..."
PLIST_PATH="$PROJECT_DIR/Sources/Resources/GoogleService-Info.plist"
if [[ -n "$APP_ID" ]]; then
    npx firebase-tools apps:sdkconfig IOS "$APP_ID" --project "$FIREBASE_PROJECT_ID" 2>&1 | \
        sed -n '/<\?xml/,/<\/plist>/p' > "$PLIST_PATH"
    log "GoogleService-Info.plist saved to Sources/Resources/"
else
    warn "Could not determine App ID — download GoogleService-Info.plist manually from Firebase Console"
fi

# ─── Enable Firestore ───
echo ""
echo "🗄️  Setting up Firestore..."
gcloud services enable firestore.googleapis.com --project="$FIREBASE_PROJECT_ID" 2>/dev/null || true
npx firebase-tools firestore:databases:create "(default)" --project "$FIREBASE_PROJECT_ID" --location=us-west1 2>&1 || {
    warn "Firestore database may already exist. Continuing..."
}
log "Firestore ready"

# ─── Enable Firebase Storage ───
echo ""
echo "📦 Enabling Firebase Storage..."
gcloud services enable firebasestorage.googleapis.com --project="$FIREBASE_PROJECT_ID" 2>/dev/null || true
log "Firebase Storage enabled"

# ─── Enable Email/Password Auth ───
echo ""
echo "🔐 Enabling Email/Password authentication..."
ACCESS_TOKEN=$(gcloud auth print-access-token 2>/dev/null || echo "")
if [[ -n "$ACCESS_TOKEN" ]]; then
    # Try to enable via API
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X PATCH \
        "https://identitytoolkit.googleapis.com/v2/projects/${FIREBASE_PROJECT_ID}/config?updateMask=signIn.email.enabled,signIn.email.passwordRequired" \
        -H "Authorization: Bearer $ACCESS_TOKEN" \
        -H "Content-Type: application/json" \
        -H "x-goog-user-project: $FIREBASE_PROJECT_ID" \
        -d '{"signIn":{"email":{"enabled":true,"passwordRequired":true}}}')
    
    if [[ "$HTTP_CODE" == "200" ]]; then
        log "Email/Password auth enabled"
    else
        warn "Could not enable auth via API (HTTP $HTTP_CODE)."
        warn "Please enable Email/Password in Firebase Console:"
        warn "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID}/authentication/providers"
    fi
else
    warn "gcloud not authenticated — enable Email/Password auth manually:"
    warn "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID}/authentication/providers"
fi

# ─── Deploy Firestore Rules ───
echo ""
echo "📜 Deploying Firestore security rules..."
RULES_DIR=$(mktemp -d)
cat > "$RULES_DIR/firebase.json" << 'JSON'
{"firestore":{"rules":"firestore.rules"}}
JSON
cat > "$RULES_DIR/.firebaserc" << RC
{"projects":{"default":"${FIREBASE_PROJECT_ID}"}}
RC
cat > "$RULES_DIR/firestore.rules" << 'RULES'
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /users/{userId}/{document=**} {
      allow read, write: if request.auth != null && request.auth.uid == userId;
    }
  }
}
RULES
cd "$RULES_DIR" && npx firebase-tools deploy --only firestore:rules --project "$FIREBASE_PROJECT_ID" 2>&1 | tail -3
rm -rf "$RULES_DIR"
log "Firestore rules deployed"

# ─── Summary ───
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 Firebase setup complete!"
echo ""
echo "   Project:  $FIREBASE_PROJECT_ID"
echo "   Bundle:   $BUNDLE_ID"
echo "   Console:  https://console.firebase.google.com/project/$FIREBASE_PROJECT_ID"
echo ""
echo "   ✓ GoogleService-Info.plist downloaded"
echo "   ✓ Firestore database created"
echo "   ✓ Security rules deployed"  
echo "   ✓ Firebase Storage enabled"
echo ""
if [[ "$HTTP_CODE" != "200" ]] 2>/dev/null; then
    echo "   ⚠ Email/Password auth — enable manually in Firebase Console"
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
