//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import Foundation
import Spezi
import SpeziScheduler
import SpeziViews


@Observable
final class {{ProjectName}}Scheduler: Module, DefaultInitializable, EnvironmentAccessible {
    @Dependency(Scheduler.self) @ObservationIgnored private var scheduler

    @MainActor var viewState: ViewState = .idle


    init() {}


    /// Add or update the current list of tasks upon app startup.
    @MainActor
    func configure() {
        do {
            try scheduler.createOrUpdateTask(
                id: "daily-check-in",
                title: "Daily Check-In",
                instructions: "Please complete your daily health check-in.",
                category: .questionnaire,
                schedule: .daily(hour: 8, minute: 0, startingAt: .today)
            )
        } catch {
            viewState = .error(
                AnyLocalizedError(
                    error: error,
                    defaultErrorDescription: "Failed to create or update scheduled tasks."
                )
            )
        }
    }
}
