//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziScheduler
import SpeziSchedulerUI
import SpeziViews
import SwiftUI


struct EventView: View {
    let event: Event

    var body: some View {
        InstructionsTile(event) {
            completeEvent(event)
        }
    }

    private func completeEvent(_ event: Event) {
        do {
            try event.complete()
        } catch {
            // Event completion was prevented by task completion policy
        }
    }
}
