//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziScheduler
import SpeziViews
import SwiftUI


struct EventView: View {
    let event: Event

    @Environment({{ProjectName}}Scheduler.self) private var scheduler


    var body: some View {
        InstructionsTile(event) {
            action
        }
    }

    @ViewBuilder private var action: some View {
        if event.complete {
            Button(action: {}) {
                Label("Completed", systemImage: "checkmark.circle.fill")
            }
            .tint(.green)
            .disabled(true)
        } else {
            Button(action: markComplete) {
                Label("Mark Complete", systemImage: "checkmark.circle")
            }
            .tint(.accentColor)
        }
    }

    private func markComplete() {
        Task {
            try? await event.complete()
        }
    }
}
