//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziScheduler
import SpeziViews
import SwiftUI


struct ScheduleView: View {
    @Binding var presentingAccount: Bool

    @EventQuery(in: Date.today..<Date.tomorrow) private var events: [Event]


    var body: some View {
        NavigationStack {
            Group {
                if events.isEmpty {
                    ContentUnavailableView(
                        "No Tasks",
                        systemImage: "checkmark.circle",
                        description: Text("You have no scheduled tasks for today.")
                    )
                } else {
                    List {
                        ForEach(events) { event in
                            EventView(event: event)
                        }
                    }
                }
            }
            .navigationTitle("Schedule")
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Account", systemImage: "person.circle") {
                        presentingAccount = true
                    }
                }
            }
        }
    }
}
