//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import SpeziScheduler
import SpeziSchedulerUI
import SpeziViews
import SwiftUI


struct ScheduleView: View {
    @Binding var presentingAccount: Bool

    @State private var date = Date()


    var body: some View {
        NavigationStack {
            EventScheduleList(date: date) { event in
                InstructionsTile(event) {
                    do {
                        try event.complete()
                    } catch {
                        // Event completion was prevented
                    }
                }
            }
            .navigationTitle("Schedule")
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Account", systemImage: "person.circle") {
                        presentingAccount = true
                    }
                }
            }
        }
    }
}
