//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import Foundation
import Spezi
import SpeziScheduler
import SpeziViews


@Observable
final class {{ProjectName}}Scheduler: Module, DefaultInitializable, EnvironmentAccessible {
    @Dependency(Scheduler.self) @ObservationIgnored private var scheduler

    @MainActor var viewState: ViewState = .idle


    init() {}


    /// Add or update the current list of tasks upon app startup.
    func configure() {
        do {
{{schedulerTaskDefinitions}}
        } catch {
            viewState = .error(
                AnyLocalizedError(
                    error: error,
                    defaultErrorDescription: "Failed to create or update scheduled tasks."
                )
            )
        }
    }
}
