//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

import FirebaseFirestore
import FirebaseStorage
import Spezi
import SpeziAccount
import SpeziFirebaseAccount


final class FirebaseConfiguration: Module, DefaultInitializable, @unchecked Sendable {
    enum ConfigurationError: Error {
        case userNotAuthenticatedYet
    }

    static var userCollection: CollectionReference {
        Firestore.firestore().collection("users")
    }


    @Application(\.logger) private var logger

    @Dependency(Account.self) private var account: Account?
    @Dependency(FirebaseAccountService.self) private var accountService: FirebaseAccountService?


    @MainActor var userDocumentReference: DocumentReference {
        get throws {
            guard let details = account?.details else {
                throw ConfigurationError.userNotAuthenticatedYet
            }

            return userDocumentReference(for: details.accountId)
        }
    }

    @MainActor var userBucketReference: StorageReference {
        get throws {
            guard let details = account?.details else {
                throw ConfigurationError.userNotAuthenticatedYet
            }

            return Storage.storage().reference().child("users/\(details.accountId)")
        }
    }


    init() {}


    func userDocumentReference(for accountId: String) -> DocumentReference {
        Self.userCollection.document(accountId)
    }
}
