//
// This source file is part of the {{ProjectName}} project
// Generated by SpeziVibe (https://github.com/StanfordSpezi/SpeziVibe)
//
// SPDX-License-Identifier: MIT
//

@preconcurrency import FirebaseFirestore
@preconcurrency import FirebaseStorage
import OSLog
@preconcurrency import PDFKit.PDFDocument
import Spezi
import SpeziAccount
import SpeziConsent
import SpeziFirebaseAccount
import SpeziFirestore
import SwiftUI
// __INJECT_STANDARD_IMPORTS__


actor {{ProjectName}}Standard: Standard,
                               EnvironmentAccessible,
                               AccountNotifyConstraint
                               // __INJECT_STANDARD_CONFORMANCES__
                               {
    @Application(\.logger) private var logger

    @Dependency(FirebaseConfiguration.self) private var configuration

    // __INJECT_STANDARD_DEPENDENCIES__

    init() {}


    func respondToEvent(_ event: AccountNotifications.Event) async {
        if case let .deletingAccount(accountId) = event {
            do {
                try await configuration.userDocumentReference(for: accountId).delete()
            } catch {
                logger.error("Could not delete user document: \(error)")
            }
        }
    }

    /// Stores the given consent form in the user's document directory with a unique timestamped filename.
    func store(consent: ConsentDocument) async throws {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd_HHmmss"
        let dateString = formatter.string(from: Date())
        let exportOptions = ConsentDocument.ExportConfiguration(paperSize: .usLetter)

        guard !FeatureFlags.disableFirebase else {
            guard let basePath = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
                logger.error("Could not create path for writing consent form to user document directory.")
                return
            }

            let filePath = basePath.appending(path: "consentForm_\(dateString).pdf")
            try await consent.export(using: exportOptions).pdf.write(to: filePath)
            return
        }

        do {
            guard let consentPDFData = try? await consent.export(using: exportOptions).pdf.dataRepresentation() else {
                logger.error("Could not store consent form.")
                return
            }

            let metadata = StorageMetadata()
            metadata.contentType = "application/pdf"
            _ = try await configuration.userBucketReference
                .child("consent/\(dateString).pdf")
                .putDataAsync(consentPDFData, metadata: metadata) { @Sendable _ in }
        } catch {
            logger.error("Could not store consent form: \(error)")
        }
    }

    // __INJECT_STANDARD_METHODS__
}
